### ISSUE TITLE
MultiPlayer Crash

### ISSUE THREAD

**Issue by itravers** [ChicoSystems/QuizGame#1]
user disconnected: Isaac Travers from: Isaac Travers-122
GET /rightanswer/jQuestion/580bf082fcbec2c1d89c7695 200 94.766 ms - 29
GET /rightanswer/jQuestion/580bf082fcbec2c1d89c7695 200 94.766 ms - 29
addUser - username: Isaac Travers  id: 5a35c656dc3e9479b0c1f9d8
users told to remove themselves from lobby
GET /isloggedin 200 47.242 ms - 4
GET /isloggedin 200 47.242 ms - 4
/home/slack/apps/QuizGame/routes/socketApi.js:274
    var difficulty = rooms[roomName].difficulty;
                                     ^

TypeError: Cannot read property 'difficulty' of undefined
    at Socket.<anonymous> (/home/slack/apps/QuizGame/routes/socketApi.js:274:38)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at /home/slack/apps/QuizGame/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quizgame@2.0.2 start: `node ./bin/www`
npm ERR! Exit status 1

**Comment by itravers** [comment]
Should be fixed by commit 2374b63
